name: r2d m2d auto approve
on:
  pull_request:
    branches:
      - develop
jobs:
  auto-approve:
    if: ${{ github.event.pull_request.head.ref == 'master' || github.event.pull_request.head.ref == 'release' }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Approve PR
        uses: hmarr/auto-approve-action@v4
